### ISSUE TITLE
SDT on mac for Pd doesn't work

### ISSUE THREAD

**Issue by porres** [SkAT-VG/SDT#17]
I downloaded the latest Mac version here https://github.com/SkAT-VG/SDT/releases/tag/v080-Max3.0-Pd0.95

more specifically here https://github.com/SkAT-VG/SDT/releases/download/v080-Max3.0-Pd0.95/SDT_macosx_pd_0.95-080.zip

Externals just do not load and I get the following error:

_/Users/porres/Downloads/SDT/SDT.pd_darwin: dlopen(/Users/porres/Downloads/SDT/SDT.pd_darwin, 10): Symbol not found: _json_builder_extra
  Referenced from: /Users/porres/Downloads/SDT/SDT.pd_darwin
  Expected in: flat namespace
 in /Users/porres/Downloads/SDT/SDT.pd_darwin_
 
 I tested with Pd 0.51-4, both 64 and 32 bits versions. I'm running macOS moojave.

<img width="871" alt="Screen Shot 2021-04-30 at 12 44 59" src="https://user-images.githubusercontent.com/5360142/116721175-6a254680-a9b3-11eb-859e-6a9bd85e5c3a.png">

ps. Also, the documentation should really use [declare -lib SDT] so the externals are properly loaded. You can also use "[r pd-dsp-started]" instead of what you're using here with [r pd] + [route dsp], etc. And please consider uploading the package to 'deken'

**Comment by ChromaticIsobar** [comment]
Thanks for reporting this @porres , we think we have identified what may be the cause of this issue.
We hope to get back to you soon with a solution.

Most of our recent development was towards the release to the Max package manager and Pd development has been lagging behind, unfortunately. All patches in the documentation are old and need to be updated, so your feedback is very valuable to us and we encourage you to tell us of any other issues that you find.
Probably, we will consider uploading to deken when that work will have been done.

**Comment by ChromaticIsobar** [comment]
The [new release](https://github.com/SkAT-VG/SDT/releases/tag/v081-Max3.0-Pd0.96) includes a fix for this issue.
Thank you again for reporting this.
