### ISSUE TITLE
windows build failure

### ISSUE THREAD

**Issue by flecheria** [SkAT-VG/SDT#2]
Hi
problem compiling with Windows here. It seems like it doesn't find sdt.pitchshift~.def

process_begin: CreateProcess(NULL, cp Info.def ../../src/Max6/sdt.pitchshift~.def, ...) failed.

```
c:\Program Files (x86)\Cycling '74\third_parts\SDT\build\windows>mingw32-make
gcc -shared -L../../3rdparty/fftw3/windows ../../src/SDT/SDTOscillators.o ../../src/SDT/SDTControl.o ../../src/SDT/SDTAnalysis.o ../../src/SDT/SDTStructs.o ../../src/SDT/SDTInteractors.o ../../src/SDT/SDTGases.o ../../src/SDT/SDTFilters.o ../../src/SDT/SDTEffects.o ../../src/SDT/SDTSolids.o ../../src/SDT/SDTDCMotor.o ../../src/SDT/SDTCommon.o ../../src/SDT/SDTLiquids.o ../../src/SDT/SDTResonators.o ../../src/SDT/SDTMotor.o -o ../../src/SDT/libSDT.dll -lfftw3-3
gcc -Wall -Wno-unknown-pragmas -Werror -DDENORM_WANT_FIX=1 -DNO_TRANSLATION_SUPPORT=1 -DC74_NO_DEPRECATION \
-DWIN_VERSION -DWIN_EXT_VERSION -fvisibility=hidden \
-I../../3rdparty/Max6SDK/max-includes -I../../3rdparty/Max6SDK/msp-includes -I../../3rdparty/Max6SDK/jit-includes \
-I../../src -c ../../src/Max6/sdt.pitchshift~.c -o ../../src/Max6/sdt.pitchshift~.o
cp Info.def ../../src/Max6/sdt.pitchshift~.def
process_begin: CreateProcess(NULL, cp Info.def ../../src/Max6/sdt.pitchshift~.def, ...) failed.
make (e=2): Impossibile trovare il file specificato.
mingw32-make: *** [../../src/Max6/sdt.pitchshift~.mxe] Error 2
rm ../../src/Max6/sdt.pitchshift~.o

c:\Program Files (x86)\Cycling '74\third_parts\SDT\build\windows>mingw32-make
gcc -shared -L../../3rdparty/fftw3/windows ../../src/SDT/SDTOscillators.o ../../src/SDT/SDTControl.o ../../src/SDT/SDTAnalysis.o ../../src/SDT/SDTStructs.o ../../src/SDT/SDTInteractors.o ../../src/SDT/SDTGases.o ../../src/SDT/SDTFilters.o ../../src/SDT/SDTEffects.o ../../src/SDT/SDTSolids.o ../../src/SDT/SDTDCMotor.o ../../src/SDT/SDTCommon.o ../../src/SDT/SDTLiquids.o ../../src/SDT/SDTResonators.o ../../src/SDT/SDTMotor.o -o ../../src/SDT/libSDT.dll -lfftw3-3
gcc -Wall -Wno-unknown-pragmas -Werror -DDENORM_WANT_FIX=1 -DNO_TRANSLATION_SUPPORT=1 -DC74_NO_DEPRECATION \
-DWIN_VERSION -DWIN_EXT_VERSION -fvisibility=hidden \
-I../../3rdparty/Max6SDK/max-includes -I../../3rdparty/Max6SDK/msp-includes -I../../3rdparty/Max6SDK/jit-includes \
-I../../src -c ../../src/Max6/sdt.pitchshift~.c -o ../../src/Max6/sdt.pitchshift~.o
cp Info.def ../../src/Max6/sdt.pitchshift~.def
process_begin: CreateProcess(NULL, cp Info.def ../../src/Max6/sdt.pitchshift~.def, ...) failed.
make (e=2): Impossibile trovare il file specificato.
mingw32-make: *** [../../src/Max6/sdt.pitchshift~.mxe] Error 2
rm ../../src/Max6/sdt.pitchshift~.o
```

Hints? Thanks

**Comment by singintime** [comment]
It looks more like it doesn't find the copy (cp) command. The Windows
makefile doesn't work directly from the windows console, it should be
executed inside a unix-like shell (MSYS or Cygwin).

Best Regards,
Stefano
Il 17/ott/2015 17:16, "paolo cappelletto" <notifications@github.com> ha
scritto:

**Comment by flecheria** [comment]
Ok I'm compiling from MSYS now but still there's something...
Compiler points to sed with wrong option -i (maybe line 29 on make file? )

```
Paolo@PAOLO-PC /c/Users/Paolo/Documents/SDT/build/windows
$ make
gcc -shared -L../../3rdparty/fftw3/windows ../../src/SDT/SDTAnalysis.o ../../src/SDT/SDTCommon.o ../../src/SDT/SDTControl.o ../../src/SDT/SDTDCMotor.o ../../src/SDT/SDTEffects.o ../../src/SDT/SDTFilters.o ../../src/SDT/SDTGases.o ../../src/SDT/SDTInteractors.o ../../src/SDT/SDTLiquids.o ../../src/SDT/SDTMotor.o ../../src/SDT/SDTOscillators.o ../../src/SDT/SDTResonators.o ../../src/SDT/SDTSolids.o ../../src/SDT/SDTStructs.o -o ../../src/SDT/libSDT.dll -lfftw3-3
gcc -Wall -Wno-unknown-pragmas -Werror -DDENORM_WANT_FIX=1 -DNO_TRANSLATION_SUPPORT=1 -DC74_NO_DEPRECATION \
        -DWIN_VERSION -DWIN_EXT_VERSION -fvisibility=hidden \
        -I../../3rdparty/Max6SDK/max-includes -I../../3rdparty/Max6SDK/msp-includes -I../../3rdparty/Max6SDK/jit-includes \
        -I../../src -c ../../src/Max6/sdt.bubble~.c -o ../../src/Max6/sdt.bubble~.o
cp Info.def ../../src/Max6/sdt.bubble~.def
sed -i ../../src/Max6/sdt.bubble~.def -e s/\${PRODUCT_NAME}/sdt.bubble~/g 
sed: invalid option -- i
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  -c  --nocr     turn off \r$ translation; must be first switch on command line
      --help     display this help and exit
  -V, --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

E-mail bug reports to: bug-gnu-utils@gnu.org .
Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
make: *** [../../src/Max6/sdt.bubble~.mxe] Error 4
rm ../../src/Max6/sdt.bubble~.o
```

**Comment by singintime** [comment]
Hmmm weird, option -i is perfectly valid on my version of sed... please try
with a full installation of MinGW + MSYS through their installer manager:

http://sourceforge.net/projects/mingw/files/latest/download

referring to the MinGW "Getting started" documentation page for proper
installation:

http://www.mingw.org/wiki/Getting_Started

If problems persist, I can build on my machine and send you the precompiled
binaries.

SB

**Comment by flecheria** [comment]
It persist also with a new installation of MInGW + MSYS. I try also with the mac but I have some issue also there but i think it's more a problem of my 10.6 Macbook with GCC.

By the way if you can send me a build for mac or pc you do to me a great favor.
Let me konw

Is it possible to build creating a project from Visual Studio or Code:Blocks? I haven't tried.. maybe in the next days

Thanks

**Comment by singintime** [comment]
Caro Paolo,

Avevo proseguito in inglese per continuità con i tuoi messaggi, ma essendo
entrambi italiani se per te va bene passerei alla nostra lingua madre :)

In allegato trovi uno zip con il Sound Design Toolkit compilato per Max 6 e
7 sotto Windows. Per farlo funzionare dovrebbe essere sufficiente estrarre
il pacchetto nella cartella "packages" della tua installazione di Max.
Attenzione che essendo compilati con mingw32, gli external funzionano solo
con Max in modalità 32 bit! Per la versione a 64 bit ci stiamo ancora
lavorando.

A presto,
Stefano

**Comment by flecheria** [comment]
Grazie. però non vedo materiale allegato, forse la cosa più semplice è caricarlo su un dropbox qualsiasi. E poi chiudiamo la issue.

**Comment by sone** [comment]
Hi, it's an old thread but because this issue is still open I would like to ask if it is possible to compile for windows 64bit? 
A second question I have is if a development environment like MinGW + MSYS or Visual Studio has any negativ influences on the audio realtime capabilities of a windows DAW system? I switched from macOS to windows just a year ago and it is a big effort to set up a dedicated windows 10 DAW at least on my computer so I'm afraid if there are services and processes always running if such a development environmet is installed.

**Comment by singintime** [comment]
Hi Johannes,

I have never tried to build for Windows 64 bits but it theory it should be
possible, setting up the right environment and pointing to the right
compiler in the Makefile. Development and use of the SDT is mostly carried
out on macs so there weren't many occasions to test it under windows.
Regarding the second question I would say no, the MinGW/MSYS process runs
only when its terminal is open.

I'll let you know if I have time and opportunity to compile on Win64. For
the moment the Win32 binaries should work for you... don't they?

Cheers,
Stefano

**Comment by JMUB** [comment]
Hello,

I downloaded the precompiled binaries for PureData. I copied the folder "SDT_Pd" for Win32 in the "externals" folder of my Pd installation.

I can see the SDT patches via the patches browser but when I open any of then I get a "couldn't create..." message.  I have Pd 0.48-1 and Windows 7 32 bits.

Am I missing any install step?

**Comment by stepap** [comment]
Hi @JMUB sorry for the huge delay. Did you succeed? The latest version should work fine on Pd/Win32.

**Comment by JMUB** [comment]
> 
> 
> Hi @JMUB sorry for the huge delay. Did you succeed? The latest version should work fine on Pd/Win32.

Hello, I am not using Win32 anymore.

**Comment by stepap** [comment]
> > Hi @JMUB sorry for the huge delay. Did you succeed? The latest version should work fine on Pd/Win32.
> 
> Hello, I am not using Win32 anymore.

Thanks for letting me know
