### ISSUE TITLE
error loading libSDT.so in Puredata (linux)

### ISSUE THREAD

**Issue by jyg** [SkAT-VG/SDT#20]
Issue with puredata on linux 64 (Ubuntu 18.04 LTS, Pd 0.51.3) using precompiled release (v081-Max3.0-Pd0.96). SDT.pd_linux tries to load libSDT.so but fails, even if I put this shared lib in the same directory as SDT.pd_linux :
`SDT.pd_linux: libSDT.so: cannot open shared object file: No such file or directory
`

**Comment by stepap** [comment]
Hi @jyg at the moment I cannot test on Linux but I forwarded your report to another developer who can. Did you try copying the SDT shared core library into /usr/lib?

**Comment by jyg** [comment]
> Did you try copying the SDT shared core library into /usr/lib?

Yes, This fixed the issus. Thanks !
