### ISSUE TITLE
Linux - fail to create objects

### ISSUE THREAD

**Issue by JMUB** [SkAT-VG/SDT#3]
Hello,

I compiled the SDT from the source in Linux (Ubuntu 16.04 LTS, Pd 0.46.7).

After installation the SDT patches are available in Pd's patch browser, however when I open any of them I get an "..couldn't create" error message from Pd.

Below you can see the results displayed in the terminal for the make and install steps.

Any hints?

Thanks in advance. 

`jm@jm-sf:~/Downloads/SDT-master/build/linux$ sudo make
[sudo] Passwort für jm: 
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTMotor.c -o ../../src/SDT/SDTMotor.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTLiquids.c -o ../../src/SDT/SDTLiquids.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTCommon.c -o ../../src/SDT/SDTCommon.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTGases.c -o ../../src/SDT/SDTGases.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTAnalysis.c -o ../../src/SDT/SDTAnalysis.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTDCMotor.c -o ../../src/SDT/SDTDCMotor.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTEffects.c -o ../../src/SDT/SDTEffects.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTResonators.c -o ../../src/SDT/SDTResonators.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTSolids.c -o ../../src/SDT/SDTSolids.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTFilters.c -o ../../src/SDT/SDTFilters.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTFFT.c -o ../../src/SDT/SDTFFT.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTInteractors.c -o ../../src/SDT/SDTInteractors.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTStructs.c -o ../../src/SDT/SDTStructs.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTControl.c -o ../../src/SDT/SDTControl.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTComplex.c -o ../../src/SDT/SDTComplex.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTOscillators.c -o ../../src/SDT/SDTOscillators.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -c ../../src/SDT/SDTDemix.c -o ../../src/SDT/SDTDemix.o
gcc -shared ../../src/SDT/SDTMotor.o ../../src/SDT/SDTLiquids.o ../../src/SDT/SDTCommon.o ../../src/SDT/SDTGases.o ../../src/SDT/SDTAnalysis.o ../../src/SDT/SDTDCMotor.o ../../src/SDT/SDTEffects.o ../../src/SDT/SDTResonators.o ../../src/SDT/SDTSolids.o ../../src/SDT/SDTFilters.o ../../src/SDT/SDTFFT.o ../../src/SDT/SDTInteractors.o ../../src/SDT/SDTStructs.o ../../src/SDT/SDTControl.o ../../src/SDT/SDTComplex.o ../../src/SDT/SDTOscillators.o ../../src/SDT/SDTDemix.o -o ../../src/SDT/libSDT.so -lc -lm
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/motor~.c -o ../../src/Pd/motor~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/reverb~.c -o ../../src/Pd/reverb~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/windcavity~.c -o ../../src/Pd/windcavity~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/windkarman~.c -o ../../src/Pd/windkarman~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/breaking~.c -o ../../src/Pd/breaking~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/friction~.c -o ../../src/Pd/friction~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/impact~.c -o ../../src/Pd/impact~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/demix~.c -o ../../src/Pd/demix~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/pitchshift~.c -o ../../src/Pd/pitchshift~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/SDT.c -o ../../src/Pd/SDT.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/myo~.c -o ../../src/Pd/myo~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/bubble~.c -o ../../src/Pd/bubble~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/scraping~.c -o ../../src/Pd/scraping~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/windflow~.c -o ../../src/Pd/windflow~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/fluidflow~.c -o ../../src/Pd/fluidflow~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/zerox~.c -o ../../src/Pd/zerox~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/bouncing~.c -o ../../src/Pd/bouncing~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/dcmotor~.c -o ../../src/Pd/dcmotor~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/inertial.c -o ../../src/Pd/inertial.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/explosion~.c -o ../../src/Pd/explosion~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/crumpling~.c -o ../../src/Pd/crumpling~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/spectralfeats~.c -o ../../src/Pd/spectralfeats~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/modal.c -o ../../src/Pd/modal.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/rolling~.c -o ../../src/Pd/rolling~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/pitch~.c -o ../../src/Pd/pitch~.o
gcc -fPIC -Wall -Wno-unknown-pragmas -Werror -O3 -I../../src -c ../../src/Pd/envelope~.c -o ../../src/Pd/envelope~.o
gcc -shared -L../../src/SDT ../../src/Pd/motor~.o ../../src/Pd/reverb~.o ../../src/Pd/windcavity~.o ../../src/Pd/windkarman~.o ../../src/Pd/breaking~.o ../../src/Pd/friction~.o ../../src/Pd/impact~.o ../../src/Pd/demix~.o ../../src/Pd/pitchshift~.o ../../src/Pd/SDT.o ../../src/Pd/myo~.o ../../src/Pd/bubble~.o ../../src/Pd/scraping~.o ../../src/Pd/windflow~.o ../../src/Pd/fluidflow~.o ../../src/Pd/zerox~.o ../../src/Pd/bouncing~.o ../../src/Pd/dcmotor~.o ../../src/Pd/inertial.o ../../src/Pd/explosion~.o ../../src/Pd/crumpling~.o ../../src/Pd/spectralfeats~.o ../../src/Pd/modal.o ../../src/Pd/rolling~.o ../../src/Pd/pitch~.o ../../src/Pd/envelope~.o -o ../../src/Pd/SDT.pd_linux -lc -lm -lSDT
jm@jm-sf:~/Downloads/SDT-master/build/linux$ sudo make install
mkdir -p /usr/lib/pd/extra/SDT
cp -a ../../src/SDT/libSDT.so /usr/lib
cp -a ../../src/Pd/*.pd_linux /usr/lib/pd/extra/SDT
cp -a ../../Pd/* /usr/lib/pd/extra/SDT`

**Comment by lonce** [comment]
1) include this in your list of paths in your pd preferences:
/usr/lib/pd/extra
2) every time you want to use SDT objects, first create and SDT object (that will load this library)
