### ISSUE TITLE
impact~

### ISSUE THREAD

**Issue by lonce** [SkAT-VG/SDT#7]
Impact~ (and all of the patches that depend on it such as rolling, etc.) are broken. I get the same behavior on both OSX and on the system I compiled on Ubuntu (18). 
It looks like something in impact~ is going to NaN, but I can't tell. 
Fluids (not dependent on impact!) work great. I'd dearly love to try the impact sounds!
Thanks,
         - lonce

**Comment by stepap** [comment]
Hi Lonce, sorry for the delayed response. SDT maintainers have changed lately.
Does it still happen with the current version?
